---
- name: update web, nfs, lb, and db servers
  hosts: webservers, nfs, db, lb
  remote_user: ec2-user
  become: yes
  become_user: root
  tasks:
  - name: delete wireshark
    yum:
      name: wireshark
      state: removed
#