---
# tasks file for apache
- name: "Installing httpd software"
  package:
     name: "httpd"
     state: present
- name: "Installing php software for php files"
  package: 
     name: "php"
- name: "copying php file to document root"     
  copy:
     src: "g.php"
     dest: "/var/www/html/index.php"
- name: "starting services"
  service: 
     name: "httpd"
     state: started
- name: "updating firewall rules for httpd"
  firewalld:
        port: 80/tcp
        immediate: yes
        permanent: yes
        state: enabled
